from __future__ import annotations

from typing import Protocol, runtime_checkable

from . import constants


@runtime_checkable
class SystemCheckerProtocol(Protocol):
    def check_git(self) -> None: ...

    def check_docker(self) -> None: ...

    def check_running_containers(self) -> None: ...

    def check_docker_compose(self) -> None: ...

    def check_file_system(self) -> None: ...

    def check_free_space_for_odoo_developing(
        self, free_space_size: float = constants.FREE_SPACE_FOR_USAGE
    ) -> None: ...


@runtime_checkable
class PrepareProjectServicesProtocol(Protocol):
    def map_folders(self) -> None: ...

    def generate_dockerfile(self) -> None: ...

    def generate_dockerignore(self) -> None: ...

    def generate_config_file(self) -> None: ...

    def generate_docker_compose_file(self) -> None: ...

    def checkout_dependencies(self, lock_manager=None) -> None: ...

    def update_links(self) -> None: ...

