from __future__ import annotations

from typing import Protocol, runtime_checkable

from . import constants


@runtime_checkable
class SystemCheckerProtocol(Protocol):
    def check_git(self) -> None: ...

    def check_docker(self) -> None: ...

    def check_running_containers(self) -> None: ...

    def check_docker_compose(self) -> None: ...

    def check_file_system(self) -> None: ...

    def check_free_space_for_odoo_developing(
        self, free_space_size: float = constants.FREE_SPACE_FOR_USAGE
    ) -> None: ...


@runtime_checkable
class CreateProjectEnvironmentProtocol(Protocol):
    def map_folders(self) -> None: ...

    def generate_dockerfile(self) -> None: ...

    def generate_dockerignore(self) -> None: ...

    def generate_config_file(self) -> None: ...

    def generate_docker_compose_file(self) -> None: ...

    def checkout_dependencies(self) -> None: ...

    def update_links(self) -> None: ...

    def update_vscode_debugger_launcher(self) -> None: ...

    def generate_vscode_settings_json(self) -> None: ...

    def download_odoo_repository(self) -> None: ...

    def download_odoo_nightly_build(self) -> None: ...

    def build_base_image(self) -> None: ...

    def ensure_base_image(self) -> None: ...

    def prepare_ci_build_context(self) -> None: ...

    def generate_ci_dockerfile(self) -> str: ...

    def build_ci_image(self) -> None: ...
