# #MESSAGE#

services:
  {DATABASE_NAME_INSTANCE}:
    image: postgres:{POSTGRES_VERSION}
    user: root
    tty: true
    ports:
      - {POSTGRES_PORT_MAP}
    environment:
      - POSTGRES_PASSWORD={POSTGRES_ODOO_PASS}
      - POSTGRES_USER={POSTGRES_ODOO_USER}
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  odoo:
    image: {ODOO_IMAGE}
    user: {CURRENT_USER}
    tty: true
    depends_on:
      - {DATABASE_NAME_INSTANCE}
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONWARNINGS="ignore::DeprecationWarning:docutils"
    ports:
      - {ODOO_PORT}:{ODOO_DOCKER_PORT}
      - {GEVENT_PORT}:{GEVENT_DOCKER_PORT}
      - {DEBUGGER_PORT_MAP}

    volumes: {MAPPED_VOLUMES}

    command: {START_STRING}

volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: {POSTGRES_DATA_LOCAL_STORAGE}
