# #MESSAGE#

services:
  {DATABASE_NAME_INSTANCE}:
    image: postgres:{POSTGRES_VERSION}
    user: root
    tty: true
    ports:
      - {POSTGRES_PORT_MAP}
    environment:
      - POSTGRES_PASSWORD={POSTGRES_ODOO_PASS}
      - POSTGRES_USER={POSTGRES_ODOO_USER}
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  odoo:
    image: {ODOO_IMAGE}
    user: {CONTAINER_USER}
    tty: true
    depends_on:
      - {DATABASE_NAME_INSTANCE}
    working_dir: {DOCKER_PROJECT_DIR}
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONWARNINGS=ignore::DeprecationWarning:docutils
{ODPM_CONFIG_PATH_ENV_LINE}{START_COMMAND_BLOCK}
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib3; http=urllib3.PoolManager(); r=http.request('GET','http://localhost:{ODOO_PORT}/web'); exit(0 if r.status==200 else 1)"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - {ODOO_PORT}:{ODOO_DOCKER_PORT}
      - {GEVENT_PORT}:{GEVENT_DOCKER_PORT}
{DEV_EXTRA_PORTS}{ODOO_VOLUMES_BLOCK}

volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: {POSTGRES_DATA_LOCAL_STORAGE}
