DEVELOPER_SCENARIO = "developer"
SERVER_SCENARIO = "server"
CI_SCENARIO = "ci"
ODPM_SCENARIOS = {
    1: DEVELOPER_SCENARIO,
    2: SERVER_SCENARIO,
    3: CI_SCENARIO,
}
ODPM_SCENARIO_VALUES = frozenset(ODPM_SCENARIOS.values())
DEFAULT_ODPM_SCENARIO = DEVELOPER_SCENARIO

VENV_MODE_FRESH = "fresh"
VENV_MODE_BAKED = "baked"
VENV_MODE_VALUES = frozenset((VENV_MODE_FRESH, VENV_MODE_BAKED))

DEFAULT_ODPM_VERSION = "3.0"
ODPM_VERSION = "4.0"
